export interface CountryConfig {
  slug: string;
  label: string;
  terms: string[];
  h1: string;
  metaDesc: string;
}

export const COUNTRIES: Record<string, CountryConfig> = {
  'united-states': {
    slug: 'united-states',
    terms: ['united states', 'usa', 'america', 'american'],
    label: 'United States',
    h1: 'The Best Onlyfans Creators All Across United States',
    metaDesc: 'Discover the most popular OnlyFans creators across United States. Browse verified profiles, free accounts, and exclusive content from American creators.',
  },
  canada: {
    slug: 'canada',
    terms: ['canada', 'canadian'],
    label: 'Canada',
    h1: 'The Best Onlyfans Creators All Across Canada',
    metaDesc: 'Discover the most popular OnlyFans creators across Canada. Browse verified profiles, free accounts, and exclusive content from Canadian creators.',
  },
  argentina: {
    slug: 'argentina',
    terms: ['argentina', 'argentinian', 'argentine', 'buenos aires'],
    label: 'Argentina',
    h1: 'The Best OnlyFans Creators From Argentina',
    metaDesc: 'Discover the most popular OnlyFans creators from Argentina. Browse verified profiles, free accounts, and exclusive content from Argentine creators.',
  },
  'united-kingdom': {
    slug: 'united-kingdom',
    terms: ['united kingdom', 'uk', 'british', 'england', 'english', 'wales', 'welsh', 'scotland', 'scottish'],
    label: 'United Kingdom',
    h1: 'The Best OnlyFans Creators From the United Kingdom',
    metaDesc: 'Discover the most popular OnlyFans creators from the United Kingdom. Browse verified profiles, free accounts, and exclusive content from British creators.',
  },
  philippines: {
    slug: 'philippines',
    terms: ['philippines', 'philippine', 'filipina', 'filipinas'],
    label: 'Philippines',
    h1: 'The Best Onlyfans Creators All Across Philippines',
    metaDesc: 'Discover the most popular OnlyFans creators across Philippines. Browse verified profiles, free accounts, and exclusive content from Philippine creators.',
  },
  india: {
    slug: 'india',
    terms: ['india', 'indian'],
    label: 'India',
    h1: 'The Best Onlyfans Creators All Across India',
    metaDesc: 'Discover the most popular OnlyFans creators across India. Browse verified profiles, free accounts, and exclusive content from Indian creators.',
  },
  japan: {
    slug: 'japan',
    terms: ['japan', 'japanese'],
    label: 'Japan',
    h1: 'The Best Onlyfans Creators All Across Japan',
    metaDesc: 'Discover the most popular OnlyFans creators across Japan. Browse verified profiles, free accounts, and exclusive content from Japanese creators.',
  },
  armenia: {
    slug: 'armenia',
    terms: ['armenia', 'armenian', 'yerevan'],
    label: 'Armenia',
    h1: 'The Best OnlyFans Creators From Armenia',
    metaDesc: 'Discover the most popular OnlyFans creators from Armenia. Browse verified profiles, free accounts, and exclusive content from Armenian creators.',
  },
  australia: {
    slug: 'australia',
    terms: ['australia', 'australian', 'sydney', 'melbourne', 'brisbane'],
    label: 'Australia',
    h1: 'The Best OnlyFans Creators From Australia',
    metaDesc: 'Discover the most popular OnlyFans creators from Australia. Browse verified profiles, free accounts, and exclusive content from Australian creators.',
  },
  austria: {
    slug: 'austria',
    terms: ['austria', 'austrian', 'vienna', 'wien'],
    label: 'Austria',
    h1: 'The Best OnlyFans Creators From Austria',
    metaDesc: 'Discover the most popular OnlyFans creators from Austria. Browse verified profiles, free accounts, and exclusive content from Austrian creators.',
  },
  bahamas: {
    slug: 'bahamas',
    terms: ['bahamas', 'bahamian', 'nassau'],
    label: 'Bahamas',
    h1: 'The Best OnlyFans Creators From Bahamas',
    metaDesc: 'Discover the most popular OnlyFans creators from Bahamas. Browse verified profiles, free accounts, and exclusive content from Bahamian creators.',
  },
  barbados: {
    slug: 'barbados',
    terms: ['barbados', 'barbadian', 'bridgetown'],
    label: 'Barbados',
    h1: 'The Best OnlyFans Creators From Barbados',
    metaDesc: 'Discover the most popular OnlyFans creators from Barbados. Browse verified profiles, free accounts, and exclusive content from Barbadian creators.',
  },
  belarus: {
    slug: 'belarus',
    terms: ['belarus', 'belarusian', 'minsk'],
    label: 'Belarus',
    h1: 'The Best OnlyFans Creators From Belarus',
    metaDesc: 'Discover the most popular OnlyFans creators from Belarus. Browse verified profiles, free accounts, and exclusive content from Belarusian creators.',
  },
  belgium: {
    slug: 'belgium',
    terms: ['belgium', 'belgian', 'brussels'],
    label: 'Belgium',
    h1: 'The Best OnlyFans Creators From Belgium',
    metaDesc: 'Discover the most popular OnlyFans creators from Belgium. Browse verified profiles, free accounts, and exclusive content from Belgian creators.',
  },
  bolivia: {
    slug: 'bolivia',
    terms: ['bolivia', 'bolivian', 'la paz', 'santa cruz'],
    label: 'Bolivia',
    h1: 'The Best OnlyFans Creators From Bolivia',
    metaDesc: 'Discover the most popular OnlyFans creators from Bolivia. Browse verified profiles, free accounts, and exclusive content from Bolivian creators.',
  },
  'bosnia-and-herzegovina': {
    slug: 'bosnia-and-herzegovina',
    terms: ['bosnia', 'bosnian', 'herzegovina', 'sarajevo'],
    label: 'Bosnia and Herzegovina',
    h1: 'The Best OnlyFans Creators From Bosnia and Herzegovina',
    metaDesc: 'Discover the most popular OnlyFans creators from Bosnia and Herzegovina. Browse verified profiles, free accounts, and exclusive content from Bosnian creators.',
  },
  brazil: {
    slug: 'brazil',
    terms: ['brazil', 'brazilian', 'brasil', 'rio de janeiro', 'sao paulo'],
    label: 'Brazil',
    h1: 'The Best OnlyFans Creators From Brazil',
    metaDesc: 'Discover the most popular OnlyFans creators from Brazil. Browse verified profiles, free accounts, and exclusive content from Brazilian creators.',
  },
  bulgaria: {
    slug: 'bulgaria',
    terms: ['bulgaria', 'bulgarian', 'sofia'],
    label: 'Bulgaria',
    h1: 'The Best OnlyFans Creators From Bulgaria',
    metaDesc: 'Discover the most popular OnlyFans creators from Bulgaria. Browse verified profiles, free accounts, and exclusive content from Bulgarian creators.',
  },
  cambodia: {
    slug: 'cambodia',
    terms: ['cambodia', 'cambodian', 'phnom penh'],
    label: 'Cambodia',
    h1: 'The Best OnlyFans Creators From Cambodia',
    metaDesc: 'Discover the most popular OnlyFans creators from Cambodia. Browse verified profiles, free accounts, and exclusive content from Cambodian creators.',
  },
  chile: {
    slug: 'chile',
    terms: ['chile', 'chilean', 'santiago', 'chilena'],
    label: 'Chile',
    h1: 'The Best OnlyFans Creators From Chile',
    metaDesc: 'Discover the most popular OnlyFans creators from Chile. Browse verified profiles, free accounts, and exclusive content from Chilean creators.',
  },
  china: {
    slug: 'china',
    terms: ['china', 'chinese', 'beijing', 'shanghai'],
    label: 'China',
    h1: 'The Best OnlyFans Creators From China',
    metaDesc: 'Discover the most popular OnlyFans creators from China. Browse verified profiles, free accounts, and exclusive content from Chinese creators.',
  },
  colombia: {
    slug: 'colombia',
    terms: ['colombia', 'colombian', 'bogota', 'medellin', 'colombiana'],
    label: 'Colombia',
    h1: 'The Best OnlyFans Creators From Colombia',
    metaDesc: 'Discover the most popular OnlyFans creators from Colombia. Browse verified profiles, free accounts, and exclusive content from Colombian creators.',
  },
  'costa-rica': {
    slug: 'costa-rica',
    terms: ['costa rica', 'costa rican', 'san jose', 'tica'],
    label: 'Costa Rica',
    h1: 'The Best OnlyFans Creators From Costa Rica',
    metaDesc: 'Discover the most popular OnlyFans creators from Costa Rica. Browse verified profiles, free accounts, and exclusive content from Costa Rican creators.',
  },
  croatia: {
    slug: 'croatia',
    terms: ['croatia', 'croatian', 'zagreb'],
    label: 'Croatia',
    h1: 'The Best OnlyFans Creators From Croatia',
    metaDesc: 'Discover the most popular OnlyFans creators from Croatia. Browse verified profiles, free accounts, and exclusive content from Croatian creators.',
  },
  cuba: {
    slug: 'cuba',
    terms: ['cuba', 'cuban', 'havana', 'cubana'],
    label: 'Cuba',
    h1: 'The Best OnlyFans Creators From Cuba',
    metaDesc: 'Discover the most popular OnlyFans creators from Cuba. Browse verified profiles, free accounts, and exclusive content from Cuban creators.',
  },
  cyprus: {
    slug: 'cyprus',
    terms: ['cyprus', 'cypriot', 'nicosia'],
    label: 'Cyprus',
    h1: 'The Best OnlyFans Creators From Cyprus',
    metaDesc: 'Discover the most popular OnlyFans creators from Cyprus. Browse verified profiles, free accounts, and exclusive content from Cypriot creators.',
  },
  'czech-republic': {
    slug: 'czech-republic',
    terms: ['czech', 'czech republic', 'czechia', 'prague'],
    label: 'Czech Republic',
    h1: 'The Best OnlyFans Creators From Czech Republic',
    metaDesc: 'Discover the most popular OnlyFans creators from Czech Republic. Browse verified profiles, free accounts, and exclusive content from Czech creators.',
  },
  denmark: {
    slug: 'denmark',
    terms: ['denmark', 'danish', 'copenhagen'],
    label: 'Denmark',
    h1: 'The Best OnlyFans Creators From Denmark',
    metaDesc: 'Discover the most popular OnlyFans creators from Denmark. Browse verified profiles, free accounts, and exclusive content from Danish creators.',
  },
  'dominican-republic': {
    slug: 'dominican-republic',
    terms: ['dominican', 'dominican republic', 'santo domingo', 'dominicana'],
    label: 'Dominican Republic',
    h1: 'The Best OnlyFans Creators From Dominican Republic',
    metaDesc: 'Discover the most popular OnlyFans creators from Dominican Republic. Browse verified profiles, free accounts, and exclusive content from Dominican creators.',
  },
  ecuador: {
    slug: 'ecuador',
    terms: ['ecuador', 'ecuadorian', 'quito', 'guayaquil', 'ecuatoriana'],
    label: 'Ecuador',
    h1: 'The Best OnlyFans Creators From Ecuador',
    metaDesc: 'Discover the most popular OnlyFans creators from Ecuador. Browse verified profiles, free accounts, and exclusive content from Ecuadorian creators.',
  },
  egypt: {
    slug: 'egypt',
    terms: ['egypt', 'egyptian', 'cairo', 'alexandria'],
    label: 'Egypt',
    h1: 'The Best OnlyFans Creators From Egypt',
    metaDesc: 'Discover the most popular OnlyFans creators from Egypt. Browse verified profiles, free accounts, and exclusive content from Egyptian creators.',
  },
  'el-salvador': {
    slug: 'el-salvador',
    terms: ['el salvador', 'salvadoran', 'san salvador'],
    label: 'El Salvador',
    h1: 'The Best OnlyFans Creators From El Salvador',
    metaDesc: 'Discover the most popular OnlyFans creators from El Salvador. Browse verified profiles, free accounts, and exclusive content from Salvadoran creators.',
  },
  estonia: {
    slug: 'estonia',
    terms: ['estonia', 'estonian', 'tallinn'],
    label: 'Estonia',
    h1: 'The Best OnlyFans Creators From Estonia',
    metaDesc: 'Discover the most popular OnlyFans creators from Estonia. Browse verified profiles, free accounts, and exclusive content from Estonian creators.',
  },
  finland: {
    slug: 'finland',
    terms: ['finland', 'finnish', 'helsinki'],
    label: 'Finland',
    h1: 'The Best OnlyFans Creators From Finland',
    metaDesc: 'Discover the most popular OnlyFans creators from Finland. Browse verified profiles, free accounts, and exclusive content from Finnish creators.',
  },
  france: {
    slug: 'france',
    terms: ['france', 'french', 'paris', 'française'],
    label: 'France',
    h1: 'The Best OnlyFans Creators From France',
    metaDesc: 'Discover the most popular OnlyFans creators from France. Browse verified profiles, free accounts, and exclusive content from French creators.',
  },
  georgia: {
    slug: 'georgia',
    terms: ['georgia country', 'georgian', 'tbilisi'],
    label: 'Georgia',
    h1: 'The Best OnlyFans Creators From Georgia',
    metaDesc: 'Discover the most popular OnlyFans creators from Georgia. Browse verified profiles, free accounts, and exclusive content from Georgian creators.',
  },
  germany: {
    slug: 'germany',
    terms: ['germany', 'german', 'berlin', 'deutschland'],
    label: 'Germany',
    h1: 'The Best OnlyFans Creators From Germany',
    metaDesc: 'Discover the most popular OnlyFans creators from Germany. Browse verified profiles, free accounts, and exclusive content from German creators.',
  },
  ghana: {
    slug: 'ghana',
    terms: ['ghana', 'ghanaian', 'accra'],
    label: 'Ghana',
    h1: 'The Best OnlyFans Creators From Ghana',
    metaDesc: 'Discover the most popular OnlyFans creators from Ghana. Browse verified profiles, free accounts, and exclusive content from Ghanaian creators.',
  },
  greece: {
    slug: 'greece',
    terms: ['greece', 'greek', 'athens', 'hellenic'],
    label: 'Greece',
    h1: 'The Best OnlyFans Creators From Greece',
    metaDesc: 'Discover the most popular OnlyFans creators from Greece. Browse verified profiles, free accounts, and exclusive content from Greek creators.',
  },
  guam: {
    slug: 'guam',
    terms: ['guam', 'guamanian', 'chamorro'],
    label: 'Guam',
    h1: 'The Best OnlyFans Creators From Guam',
    metaDesc: 'Discover the most popular OnlyFans creators from Guam. Browse verified profiles, free accounts, and exclusive content from Guamanian creators.',
  },
  guatemala: {
    slug: 'guatemala',
    terms: ['guatemala', 'guatemalan', 'guatemalteca'],
    label: 'Guatemala',
    h1: 'The Best OnlyFans Creators From Guatemala',
    metaDesc: 'Discover the most popular OnlyFans creators from Guatemala. Browse verified profiles, free accounts, and exclusive content from Guatemalan creators.',
  },
  honduras: {
    slug: 'honduras',
    terms: ['honduras', 'honduran', 'tegucigalpa', 'hondureña'],
    label: 'Honduras',
    h1: 'The Best OnlyFans Creators From Honduras',
    metaDesc: 'Discover the most popular OnlyFans creators from Honduras. Browse verified profiles, free accounts, and exclusive content from Honduran creators.',
  },
  'hong-kong': {
    slug: 'hong-kong',
    terms: ['hong kong', 'hongkong', 'hk'],
    label: 'Hong Kong',
    h1: 'The Best OnlyFans Creators From Hong Kong',
    metaDesc: 'Discover the most popular OnlyFans creators from Hong Kong. Browse verified profiles, free accounts, and exclusive content from Hong Kong creators.',
  },
  hungary: {
    slug: 'hungary',
    terms: ['hungary', 'hungarian', 'budapest'],
    label: 'Hungary',
    h1: 'The Best OnlyFans Creators From Hungary',
    metaDesc: 'Discover the most popular OnlyFans creators from Hungary. Browse verified profiles, free accounts, and exclusive content from Hungarian creators.',
  },
  iceland: {
    slug: 'iceland',
    terms: ['iceland', 'icelandic', 'reykjavik'],
    label: 'Iceland',
    h1: 'The Best OnlyFans Creators From Iceland',
    metaDesc: 'Discover the most popular OnlyFans creators from Iceland. Browse verified profiles, free accounts, and exclusive content from Icelandic creators.',
  },
  indonesia: {
    slug: 'indonesia',
    terms: ['indonesia', 'indonesian', 'jakarta', 'bali'],
    label: 'Indonesia',
    h1: 'The Best OnlyFans Creators From Indonesia',
    metaDesc: 'Discover the most popular OnlyFans creators from Indonesia. Browse verified profiles, free accounts, and exclusive content from Indonesian creators.',
  },
  ireland: {
    slug: 'ireland',
    terms: ['ireland', 'irish', 'dublin'],
    label: 'Ireland',
    h1: 'The Best OnlyFans Creators From Ireland',
    metaDesc: 'Discover the most popular OnlyFans creators from Ireland. Browse verified profiles, free accounts, and exclusive content from Irish creators.',
  },
  israel: {
    slug: 'israel',
    terms: ['israel', 'israeli', 'tel aviv', 'jerusalem'],
    label: 'Israel',
    h1: 'The Best OnlyFans Creators From Israel',
    metaDesc: 'Discover the most popular OnlyFans creators from Israel. Browse verified profiles, free accounts, and exclusive content from Israeli creators.',
  },
  italy: {
    slug: 'italy',
    terms: ['italy', 'italian', 'rome', 'milan', 'italia', 'italiana'],
    label: 'Italy',
    h1: 'The Best OnlyFans Creators From Italy',
    metaDesc: 'Discover the most popular OnlyFans creators from Italy. Browse verified profiles, free accounts, and exclusive content from Italian creators.',
  },
  jamaica: {
    slug: 'jamaica',
    terms: ['jamaica', 'jamaican', 'kingston'],
    label: 'Jamaica',
    h1: 'The Best OnlyFans Creators From Jamaica',
    metaDesc: 'Discover the most popular OnlyFans creators from Jamaica. Browse verified profiles, free accounts, and exclusive content from Jamaican creators.',
  },
  kenya: {
    slug: 'kenya',
    terms: ['kenya', 'kenyan', 'nairobi'],
    label: 'Kenya',
    h1: 'The Best OnlyFans Creators From Kenya',
    metaDesc: 'Discover the most popular OnlyFans creators from Kenya. Browse verified profiles, free accounts, and exclusive content from Kenyan creators.',
  },
  latvia: {
    slug: 'latvia',
    terms: ['latvia', 'latvian', 'riga'],
    label: 'Latvia',
    h1: 'The Best OnlyFans Creators From Latvia',
    metaDesc: 'Discover the most popular OnlyFans creators from Latvia. Browse verified profiles, free accounts, and exclusive content from Latvian creators.',
  },
  lebanon: {
    slug: 'lebanon',
    terms: ['lebanon', 'lebanese', 'beirut'],
    label: 'Lebanon',
    h1: 'The Best OnlyFans Creators From Lebanon',
    metaDesc: 'Discover the most popular OnlyFans creators from Lebanon. Browse verified profiles, free accounts, and exclusive content from Lebanese creators.',
  },
  lithuania: {
    slug: 'lithuania',
    terms: ['lithuania', 'lithuanian', 'vilnius'],
    label: 'Lithuania',
    h1: 'The Best OnlyFans Creators From Lithuania',
    metaDesc: 'Discover the most popular OnlyFans creators from Lithuania. Browse verified profiles, free accounts, and exclusive content from Lithuanian creators.',
  },
  luxembourg: {
    slug: 'luxembourg',
    terms: ['luxembourg', 'luxembourgish'],
    label: 'Luxembourg',
    h1: 'The Best OnlyFans Creators From Luxembourg',
    metaDesc: 'Discover the most popular OnlyFans creators from Luxembourg. Browse verified profiles, free accounts, and exclusive content from Luxembourgish creators.',
  },
  malaysia: {
    slug: 'malaysia',
    terms: ['malaysia', 'malaysian', 'kuala lumpur'],
    label: 'Malaysia',
    h1: 'The Best OnlyFans Creators From Malaysia',
    metaDesc: 'Discover the most popular OnlyFans creators from Malaysia. Browse verified profiles, free accounts, and exclusive content from Malaysian creators.',
  },
  malta: {
    slug: 'malta',
    terms: ['malta', 'maltese', 'valletta'],
    label: 'Malta',
    h1: 'The Best OnlyFans Creators From Malta',
    metaDesc: 'Discover the most popular OnlyFans creators from Malta. Browse verified profiles, free accounts, and exclusive content from Maltese creators.',
  },
  mexico: {
    slug: 'mexico',
    terms: ['mexico', 'mexican', 'mexico city', 'guadalajara', 'mexicana'],
    label: 'Mexico',
    h1: 'The Best OnlyFans Creators From Mexico',
    metaDesc: 'Discover the most popular OnlyFans creators from Mexico. Browse verified profiles, free accounts, and exclusive content from Mexican creators.',
  },
  moldova: {
    slug: 'moldova',
    terms: ['moldova', 'moldovan', 'chisinau'],
    label: 'Moldova',
    h1: 'The Best OnlyFans Creators From Moldova',
    metaDesc: 'Discover the most popular OnlyFans creators from Moldova. Browse verified profiles, free accounts, and exclusive content from Moldovan creators.',
  },
  monaco: {
    slug: 'monaco',
    terms: ['monaco', 'monegasque', 'monte carlo'],
    label: 'Monaco',
    h1: 'The Best OnlyFans Creators From Monaco',
    metaDesc: 'Discover the most popular OnlyFans creators from Monaco. Browse verified profiles, free accounts, and exclusive content from Monégasque creators.',
  },
  montenegro: {
    slug: 'montenegro',
    terms: ['montenegro', 'montenegrin', 'podgorica'],
    label: 'Montenegro',
    h1: 'The Best OnlyFans Creators From Montenegro',
    metaDesc: 'Discover the most popular OnlyFans creators from Montenegro. Browse verified profiles, free accounts, and exclusive content from Montenegrin creators.',
  },
  morocco: {
    slug: 'morocco',
    terms: ['morocco', 'moroccan', 'casablanca', 'marrakech'],
    label: 'Morocco',
    h1: 'The Best OnlyFans Creators From Morocco',
    metaDesc: 'Discover the most popular OnlyFans creators from Morocco. Browse verified profiles, free accounts, and exclusive content from Moroccan creators.',
  },
  netherlands: {
    slug: 'netherlands',
    terms: ['netherlands', 'dutch', 'holland', 'amsterdam'],
    label: 'Netherlands',
    h1: 'The Best OnlyFans Creators From Netherlands',
    metaDesc: 'Discover the most popular OnlyFans creators from Netherlands. Browse verified profiles, free accounts, and exclusive content from Dutch creators.',
  },
  'new-zealand': {
    slug: 'new-zealand',
    terms: ['new zealand', 'nz', 'kiwi', 'auckland', 'wellington'],
    label: 'New Zealand',
    h1: 'The Best OnlyFans Creators From New Zealand',
    metaDesc: 'Discover the most popular OnlyFans creators from New Zealand. Browse verified profiles, free accounts, and exclusive content from New Zealander creators.',
  },
  nigeria: {
    slug: 'nigeria',
    terms: ['nigeria', 'nigerian', 'lagos', 'abuja'],
    label: 'Nigeria',
    h1: 'The Best OnlyFans Creators From Nigeria',
    metaDesc: 'Discover the most popular OnlyFans creators from Nigeria. Browse verified profiles, free accounts, and exclusive content from Nigerian creators.',
  },
  norway: {
    slug: 'norway',
    terms: ['norway', 'norwegian', 'oslo'],
    label: 'Norway',
    h1: 'The Best OnlyFans Creators From Norway',
    metaDesc: 'Discover the most popular OnlyFans creators from Norway. Browse verified profiles, free accounts, and exclusive content from Norwegian creators.',
  },
  pakistan: {
    slug: 'pakistan',
    terms: ['pakistan', 'pakistani', 'karachi', 'lahore', 'islamabad'],
    label: 'Pakistan',
    h1: 'The Best OnlyFans Creators From Pakistan',
    metaDesc: 'Discover the most popular OnlyFans creators from Pakistan. Browse verified profiles, free accounts, and exclusive content from Pakistani creators.',
  },
  panama: {
    slug: 'panama',
    terms: ['panama', 'panamanian', 'panama city', 'panameña'],
    label: 'Panama',
    h1: 'The Best OnlyFans Creators From Panama',
    metaDesc: 'Discover the most popular OnlyFans creators from Panama. Browse verified profiles, free accounts, and exclusive content from Panamanian creators.',
  },
  paraguay: {
    slug: 'paraguay',
    terms: ['paraguay', 'paraguayan', 'asuncion', 'paraguaya'],
    label: 'Paraguay',
    h1: 'The Best OnlyFans Creators From Paraguay',
    metaDesc: 'Discover the most popular OnlyFans creators from Paraguay. Browse verified profiles, free accounts, and exclusive content from Paraguayan creators.',
  },
  peru: {
    slug: 'peru',
    terms: ['peru', 'peruvian', 'lima', 'peruana'],
    label: 'Peru',
    h1: 'The Best OnlyFans Creators From Peru',
    metaDesc: 'Discover the most popular OnlyFans creators from Peru. Browse verified profiles, free accounts, and exclusive content from Peruvian creators.',
  },
  poland: {
    slug: 'poland',
    terms: ['poland', 'polish', 'warsaw', 'krakow', 'polska'],
    label: 'Poland',
    h1: 'The Best OnlyFans Creators From Poland',
    metaDesc: 'Discover the most popular OnlyFans creators from Poland. Browse verified profiles, free accounts, and exclusive content from Polish creators.',
  },
  portugal: {
    slug: 'portugal',
    terms: ['portugal', 'portuguese', 'lisbon', 'porto', 'portuguesa'],
    label: 'Portugal',
    h1: 'The Best OnlyFans Creators From Portugal',
    metaDesc: 'Discover the most popular OnlyFans creators from Portugal. Browse verified profiles, free accounts, and exclusive content from Portuguese creators.',
  },
  'puerto-rico': {
    slug: 'puerto-rico',
    terms: ['puerto rico', 'puerto rican', 'san juan', 'boricua'],
    label: 'Puerto Rico',
    h1: 'The Best OnlyFans Creators From Puerto Rico',
    metaDesc: 'Discover the most popular OnlyFans creators from Puerto Rico. Browse verified profiles, free accounts, and exclusive content from Puerto Rican creators.',
  },
  romania: {
    slug: 'romania',
    terms: ['romania', 'romanian', 'bucharest'],
    label: 'Romania',
    h1: 'The Best OnlyFans Creators From Romania',
    metaDesc: 'Discover the most popular OnlyFans creators from Romania. Browse verified profiles, free accounts, and exclusive content from Romanian creators.',
  },
  russia: {
    slug: 'russia',
    terms: ['russia', 'russian', 'moscow', 'saint petersburg'],
    label: 'Russia',
    h1: 'The Best OnlyFans Creators From Russia',
    metaDesc: 'Discover the most popular OnlyFans creators from Russia. Browse verified profiles, free accounts, and exclusive content from Russian creators.',
  },
  'saudi-arabia': {
    slug: 'saudi-arabia',
    terms: ['saudi arabia', 'saudi', 'riyadh', 'jeddah'],
    label: 'Saudi Arabia',
    h1: 'The Best OnlyFans Creators From Saudi Arabia',
    metaDesc: 'Discover the most popular OnlyFans creators from Saudi Arabia. Browse verified profiles, free accounts, and exclusive content from Saudi creators.',
  },
  scotland: {
    slug: 'scotland',
    terms: ['scotland', 'scottish', 'edinburgh', 'glasgow'],
    label: 'Scotland',
    h1: 'The Best OnlyFans Creators From Scotland',
    metaDesc: 'Discover the most popular OnlyFans creators from Scotland. Browse verified profiles, free accounts, and exclusive content from Scottish creators.',
  },
  serbia: {
    slug: 'serbia',
    terms: ['serbia', 'serbian', 'belgrade'],
    label: 'Serbia',
    h1: 'The Best OnlyFans Creators From Serbia',
    metaDesc: 'Discover the most popular OnlyFans creators from Serbia. Browse verified profiles, free accounts, and exclusive content from Serbian creators.',
  },
  singapore: {
    slug: 'singapore',
    terms: ['singapore', 'singaporean'],
    label: 'Singapore',
    h1: 'The Best OnlyFans Creators From Singapore',
    metaDesc: 'Discover the most popular OnlyFans creators from Singapore. Browse verified profiles, free accounts, and exclusive content from Singaporean creators.',
  },
  slovakia: {
    slug: 'slovakia',
    terms: ['slovakia', 'slovak', 'bratislava'],
    label: 'Slovakia',
    h1: 'The Best OnlyFans Creators From Slovakia',
    metaDesc: 'Discover the most popular OnlyFans creators from Slovakia. Browse verified profiles, free accounts, and exclusive content from Slovak creators.',
  },
  slovenia: {
    slug: 'slovenia',
    terms: ['slovenia', 'slovenian', 'ljubljana'],
    label: 'Slovenia',
    h1: 'The Best OnlyFans Creators From Slovenia',
    metaDesc: 'Discover the most popular OnlyFans creators from Slovenia. Browse verified profiles, free accounts, and exclusive content from Slovenian creators.',
  },
  'south-africa': {
    slug: 'south-africa',
    terms: ['south africa', 'south african', 'cape town', 'johannesburg'],
    label: 'South Africa',
    h1: 'The Best OnlyFans Creators From South Africa',
    metaDesc: 'Discover the most popular OnlyFans creators from South Africa. Browse verified profiles, free accounts, and exclusive content from South African creators.',
  },
  'south-korea': {
    slug: 'south-korea',
    terms: ['south korea', 'korean', 'seoul', 'kpop', 'k-pop'],
    label: 'South Korea',
    h1: 'The Best OnlyFans Creators From South Korea',
    metaDesc: 'Discover the most popular OnlyFans creators from South Korea. Browse verified profiles, free accounts, and exclusive content from Korean creators.',
  },
  spain: {
    slug: 'spain',
    terms: ['spain', 'spanish', 'madrid', 'barcelona', 'española'],
    label: 'Spain',
    h1: 'The Best OnlyFans Creators From Spain',
    metaDesc: 'Discover the most popular OnlyFans creators from Spain. Browse verified profiles, free accounts, and exclusive content from Spanish creators.',
  },
  'sri-lanka': {
    slug: 'sri-lanka',
    terms: ['sri lanka', 'sri lankan', 'colombo', 'ceylon'],
    label: 'Sri Lanka',
    h1: 'The Best OnlyFans Creators From Sri Lanka',
    metaDesc: 'Discover the most popular OnlyFans creators from Sri Lanka. Browse verified profiles, free accounts, and exclusive content from Sri Lankan creators.',
  },
  sweden: {
    slug: 'sweden',
    terms: ['sweden', 'swedish', 'stockholm'],
    label: 'Sweden',
    h1: 'The Best OnlyFans Creators From Sweden',
    metaDesc: 'Discover the most popular OnlyFans creators from Sweden. Browse verified profiles, free accounts, and exclusive content from Swedish creators.',
  },
  switzerland: {
    slug: 'switzerland',
    terms: ['switzerland', 'swiss', 'zurich', 'geneva'],
    label: 'Switzerland',
    h1: 'The Best OnlyFans Creators From Switzerland',
    metaDesc: 'Discover the most popular OnlyFans creators from Switzerland. Browse verified profiles, free accounts, and exclusive content from Swiss creators.',
  },
  taiwan: {
    slug: 'taiwan',
    terms: ['taiwan', 'taiwanese', 'taipei'],
    label: 'Taiwan',
    h1: 'The Best OnlyFans Creators From Taiwan',
    metaDesc: 'Discover the most popular OnlyFans creators from Taiwan. Browse verified profiles, free accounts, and exclusive content from Taiwanese creators.',
  },
  thailand: {
    slug: 'thailand',
    terms: ['thailand', 'thai', 'bangkok'],
    label: 'Thailand',
    h1: 'The Best OnlyFans Creators From Thailand',
    metaDesc: 'Discover the most popular OnlyFans creators from Thailand. Browse verified profiles, free accounts, and exclusive content from Thai creators.',
  },
  'trinidad-and-tobago': {
    slug: 'trinidad-and-tobago',
    terms: ['trinidad', 'tobago', 'trinidadian', 'port of spain'],
    label: 'Trinidad and Tobago',
    h1: 'The Best OnlyFans Creators From Trinidad and Tobago',
    metaDesc: 'Discover the most popular OnlyFans creators from Trinidad and Tobago. Browse verified profiles, free accounts, and exclusive content from Trinidadian creators.',
  },
  tunisia: {
    slug: 'tunisia',
    terms: ['tunisia', 'tunisian', 'tunis'],
    label: 'Tunisia',
    h1: 'The Best OnlyFans Creators From Tunisia',
    metaDesc: 'Discover the most popular OnlyFans creators from Tunisia. Browse verified profiles, free accounts, and exclusive content from Tunisian creators.',
  },
  turkey: {
    slug: 'turkey',
    terms: ['turkey', 'turkish', 'istanbul', 'ankara'],
    label: 'Turkey',
    h1: 'The Best OnlyFans Creators From Turkey',
    metaDesc: 'Discover the most popular OnlyFans creators from Turkey. Browse verified profiles, free accounts, and exclusive content from Turkish creators.',
  },
  ukraine: {
    slug: 'ukraine',
    terms: ['ukraine', 'ukrainian', 'kyiv', 'odessa'],
    label: 'Ukraine',
    h1: 'The Best OnlyFans Creators From Ukraine',
    metaDesc: 'Discover the most popular OnlyFans creators from Ukraine. Browse verified profiles, free accounts, and exclusive content from Ukrainian creators.',
  },
  'united-arab-emirates': {
    slug: 'united-arab-emirates',
    terms: ['uae', 'emirates', 'dubai', 'abu dhabi'],
    label: 'United Arab Emirates',
    h1: 'The Best OnlyFans Creators From United Arab Emirates',
    metaDesc: 'Discover the most popular OnlyFans creators from United Arab Emirates. Browse verified profiles, free accounts, and exclusive content from Emirati creators.',
  },
  uruguay: {
    slug: 'uruguay',
    terms: ['uruguay', 'uruguayan', 'montevideo', 'uruguaya'],
    label: 'Uruguay',
    h1: 'The Best OnlyFans Creators From Uruguay',
    metaDesc: 'Discover the most popular OnlyFans creators from Uruguay. Browse verified profiles, free accounts, and exclusive content from Uruguayan creators.',
  },
  venezuela: {
    slug: 'venezuela',
    terms: ['venezuela', 'venezuelan', 'caracas', 'venezolana'],
    label: 'Venezuela',
    h1: 'The Best OnlyFans Creators From Venezuela',
    metaDesc: 'Discover the most popular OnlyFans creators from Venezuela. Browse verified profiles, free accounts, and exclusive content from Venezuelan creators.',
  },
  vietnam: {
    slug: 'vietnam',
    terms: ['vietnam', 'vietnamese', 'ho chi minh', 'hanoi'],
    label: 'Vietnam',
    h1: 'The Best OnlyFans Creators From Vietnam',
    metaDesc: 'Discover the most popular OnlyFans creators from Vietnam. Browse verified profiles, free accounts, and exclusive content from Vietnamese creators.',
  },
};

export function getCountry(slug: string): CountryConfig | undefined {
  return COUNTRIES[slug];
}

export const ALL_COUNTRY_SLUGS = Object.keys(COUNTRIES);

// For locations page — alphabetically sorted
export const COUNTRIES_LIST = Object.values(COUNTRIES).sort((a, b) =>
  a.label.localeCompare(b.label)
);
